# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swap App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swap App

pod 'AFNetworking', '~> 3.0'
pod 'Mantle', '~> 2.0'
pod 'MBProgressHUD', '~> 1.1'
pod 'ActionSheetPicker-3.0'
pod 'TPKeyboardAvoiding', '~> 1.3'

end
